---

# unattended upgrades -might- lock you out of apt
# https://unix.stackexchange.com/questions/463498/terminate-and-disable-remove-unattended-upgrade-before-command-returns
- name: Wait for any possibly running unattended upgrade to finish
  raw: systemd-run --property="After=apt-daily.service apt-daily-upgrade.service" --wait /bin/true
  become: true

- name: Purge unattended upgrades
  raw: apt-get -y purge unattended-upgrades
  become: true
