---

  # Test if user exists, don't fail if it doesn't.
  # Register output and skip adding user if exit code is 0 == success => user exists
- name: Testing if user {{ user_name }} exists (failure is ok)
  shell: ldapid {{ user_name }}
  become: true
  ignore_errors: true
  register: command_output

- name: Adding user {{ user_name }}
  block:
    - name: Adding {{ user_name }} to ldap
      shell: ldapadduser {{ user_name }} fiwi
      become: true

    - name: Adding {{ user_name }} to fiwi
      shell: ldapaddusertogroup {{ user_name }} fiwi
      become: true

    - name: Setting {{ user_name }} pw to dummy for now ( {{ user_pw }} )
      shell: (echo {{ user_pw }}; echo {{ user_pw }}) | ldapsetpasswd {{ user_name }}
      become: true
  when: command_output.rc != 0
