---

# remove old entries
- name: Setup Hostname (0/2)
  lineinfile:
    path: /etc/hosts
    search_string: '{{ inventory_hostname }}'
    state: absent
  become: true

- name: Setup Hostname (1/2)
  lineinfile:
    path: /etc/hosts
    search_string: '{{ inventory_hostname }}'
    line: "{{ ldap_ip }} {{ inventory_hostname }}"
  become: true

- name: Setup Hostname (2/2)
  lineinfile:
    path: /etc/hosts
    search_string: '{{ ldap_fqdn }}'
    line: "{{ ldap_ip }} {{ ldap_fqdn }}"
  become: true

# be sure to use static ip addresses
- name : check for hostname in /etc/hosts
  shell: grep "{{ inventory_hostname }}" /etc/hosts
  register: static_ip
  # don't immediately crash on no match!
  failed_when: static_ip.rc == 2

# Print debug msg and exit if hostname not in /etc/hosts
- block:
  - debug:
      msg: "Fatal! Hostname not found in /etc/hosts!"
  - meta: end_play
  when: static_ip.rc != 0


- name: install slapd and ldap-utils
  apt:
    name: slapd, ldap-utils
  become: true

- name: Configure slapd manually
  pause:
    prompt: "Please connect to remote machine and configure using: 'sudo dpkg-reconfigure slapd'.\nAnswers:\n - Omit config? <NO>\n - domain name: {{ ldap_fqdn }}\n - organization: FiWi-Wue \n - admin password: {{ ldap_admin_pw }}\n - remove when purged <YES>\n - Move? <YES>\nConfirm with <enter>."

# Install TLS support
- include_tasks: TLS.yml
- include_tasks: ldap-config.yml
- include_tasks: ldapscripts.yml

- name: Add group and user categories
  copy:
    dest: "categories.ldif"
    content: |    # '"' are needed because ':' have to be escaped
      dn: ou=People,{{ ldap_dc_base }}
      objectClass: organizationalUnit
      ou: People

      dn: ou=Groups,{{ ldap_dc_base }}
      objectClass: organizationalUnit
      ou: Groups

      dn: cn=fiwi,ou=Groups,{{ ldap_dc_base }}
      objectClass: posixGroup
      cn: testgroup
      gidNumber: 5566

- name: Import categories from ldif and remove tmp file
  # passwordfile exists because of ldapscripts install
  shell: "ldapadd -x -D cn=admin,{{ ldap_dc_base }} -f categories.ldif -y /etc/ldapscripts/ldapscripts.passwd " #&& rm categories.ldif"
  become: true
  register: out

- debug: var=out.stdout_lines

- block:
  - debug:
      msg: failure adding content of ldiff!
  - meta: end_play
  when: out.stdout_lines|length == 0

    # - include_tasks: sssd.yml
