---
# notes: requires user_name

- name: Add user {{ user_name }}
  shell: (echo {{ smb_master_pw }}; echo {{ smb_master_pw }}) | smbpasswd -a {{ user_name }}
  become: true

# allow each user to ssh into its own machines
- name: Generating ssh keys for {{ user_name }} (1/3)
  shell: mkdir -p ~/.ssh && chmod 700 ~/.ssh
  become: true
  become_user: "{{ user_name }}"
  vars:
    allow_world_readable_tmpfiles: true
- name: Generating ssh keys for {{ user_name }} (2/3)
  shell: ssh-keygen -b 3072 -t rsa -f ~/.ssh/id_rsa -N ""
  become: true
  become_user: "{{ user_name }}"
  vars:
    allow_world_readable_tmpfiles: true
- name: Generating ssh keys for {{ user_name }} (3/3)
  shell: echo '# This users own local key' >> ~/.ssh/authorized_keys && cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
  become: true
  become_user: "{{ user_name }}"
  vars:
    allow_world_readable_tmpfiles: true

- name: Restart samba
  service:
    name: smbd
    state: restarted
  become: true
