---
# notes: requires user_name and add_user_server first

- name: Create credentials file for {{ user_name }}
  copy:
    dest: /etc/samba/creds/{{ user_name }}
    content: |
      username={{ user_name }}
      password={{ smb_master_pw }}
    owner: root
    group: root
    mode: '600'
  become: true

- name: Add fstab entry for {{ user_name }}
  lineinfile:
    path: /etc/fstab
    search_string: '//{{ ldap_fqdn }}/{{ user_name }}'
    line: '//{{ ldap_fqdn }}/{{ user_name }}    /home/ldap/{{ user_name }}    cifs    vers=3.0,credentials=/etc/samba/creds/{{ user_name }},nouser,dir_mode=0700,file_mode=0600,uid={{ user_name }},gid=fiwi,exec 0 0'
  become: true

- name: Add systemd mount file for {{ user_name }}
  copy:
    dest: /etc/systemd/system/home-ldap-{{ user_name }}.mount
    content: |
      [Unit]
        Description=cifs mount script
        Requires=network-online.target
        After=network-online.service
        After=sssd.service

      [Mount]
        What=//{{ ldap_fqdn }}/{{ user_name }}
        Where=/home/ldap/{{ user_name }}
        Options=credentials=/etc/samba/creds/{{ user_name }},rw,dir_mode=0700,file_mode=0600,uid={{ user_name }},gid=fiwi
        Type=cifs

      [Install]
        WantedBy=multi-user.target
  become: true

- name: Enable systemd mounting for {{ user_name }} mount file
  shell: systemctl enable --now home-ldap-{{ user_name }}.mount
  become: true

- name: Mounting missing shares
  shell: mount -a
  become: true
