---

- name: "Install needed tools: rng-tools, bash-completion, vim, chrony, tmux, ranger,...\nMight take a few minutes."
  apt:
    name: "{{ item }}"
  become: true
  loop:
    - rng-tools
    - bash-completion
    - vim
    - chrony
    - tmux
    - ranger
    - gfortran-8
    - acl
    - unzip
    - dos2unix
    - gnuplot-nox
    - cpufrequtils

- include_tasks: fortran.yml
- include_tasks: set_config.yml
- include_tasks: workerlist.yml

- name: "Make sure all hosts know each other"
  lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[host_item]['ansible_host'] }} {{ host_item }}"
  become: true
  loop: "{{ groups['vms'] }}"
  loop_control:
    loop_var: host_item
