---
 - name: "Install needed tools: rng-tools, bash-completion, vim, chrony, tmux, ranger, gfortran"
   apt:
     name: rng-tools, bash-completion, vim, chrony, tmux, ranger, gfortran
   become: true
