---

users_to_add:
  - name: 'test01'
    passwd: '6789'

  - name: 'test02'
    passwd: 'abc'

  - name: 'test03'
    passwd: 'lkjl'

  - name: 'test04'
    passwd: '9876'

  - name: 'mfeldman'
    passwd: 'MzEyNDIK'

  - name: 'hfehr'
    passwd: 'OTUwNQo='

  - name: 'afroehlich'
    passwd: 'MzUwNQo='

  - name: 'acc102'
    passwd: '9876'

  - name: 'acc103'
    passwd: '9876'

  - name: 'acc104'
    passwd: '9876'

  - name: 'acc105'
    passwd: '9876'

  - name: 'acc106'
    passwd: '9876'

  - name: 'acc107'
    passwd: '9876'

