---

- name: Install updates
  hosts: vms
  tasks:

    - name: Purge unattended upgrades
      include_role:
        name: purge_unattended_upgrades
        tasks_from: main.yml

    - name: Update & Upgrade
      apt:
        update_cache: yes
        upgrade: full
        autoremove: yes
      become: yes


