---

- hosts: "{{ ldap_client | default('fvm-02') }}"
  pre_tasks:
    - name: include env vars
      include_vars: vault_vars
    - name: include config
      include_vars: ldap_config.yml

  roles:
    - purge_unattended_upgrades
    - apt_update_cache
    - setup_timezone

  tasks:
    - name: Add {{ ldap_host }} to /etc/hosts
      lineinfile:
        path: /etc/hosts
        regex: '^{{ ldap_ip }}'
        line: '{{ ldap_ip }} {{ ldap_fqdn }}'
      become: true
    - name: Pull CA-cert from ldap server
      fetch:
        src: /usr/local/share/ca-certificates/fiwi_ca_self-signed_cert.crt
        dest: /tmp/xyzzzzz
      delegate_to: "{{ ldap_host }}"
    - name: Push CA-cert to client
      copy:
        src: /tmp/xyzzzzz
        dest: /usr/local/share/ca-certificates/fiwi-ca-cert.crt
      become: true

      #synchronize:
      #  src: /usr/local/share/ca-certificates/fiwi_ca_self-signed_cert.crt
      #  dest: /usr/local/share/ca-certificates/fiwi-ca-cert.crt
      #delegate_to: "{{ ldap_host }}"
      #become: true

    - name: Update certificates
      shell: "update-ca-certificates"
      become: true
    - include_role:
        name: setup_ldap
        tasks_from: sssd.yml


