---

- hosts: ldap
  pre_tasks:
    - name: include config
      include_vars: ../configs/ldap_config.yml

  roles:
    - purge_unattended_upgrades
    - apt_update_cache
    - setup_apache

  tasks:
    - name: Copy bin/
      include_role:
        name: copy_landingpage
        tasks_from: main.yml
